补全：archery 和 goinception 剩余的数据库变量，优化 archery 的一些注释
douban/charts pull request #45
Opened 2023-02-16 09:15 UTC by Spinestars

2023-02-16 13:10 UTC, LeoQuote commented on charts/goinception/values.yaml
> +      backup_user="BACKUP_USER_PLACEHOLDER"
我设计中, 这三个变量都是不敏感的, 所以我设计是让用户直接写明文, 你觉得呢?

2023-02-25 08:22 UTC, Spinestars commented on charts/goinception/values.yaml
> +      backup_user="BACKUP_USER_PLACEHOLDER"
其实，是在 archery 中的 values.yaml 中，涉及到 goinception 的时候，goinception.initEnv 当前只支持了 BACKUP_PASSWORD。
所以提交的这个主要是为了支持 archery 的 values.yaml 下 goinception.initEnv 支持其余几个 backup_host，backup_port，backup_user

2023-02-25 08:46 UTC, LeoQuote commented on charts/goinception/values.yaml
> +      backup_user="BACKUP_USER_PLACEHOLDER"
行吧, 给用户一些自由, 因为 archery 依赖 goinception 的chart , 你先提 goinception chart 的升级吧, archery 的chart 修改另起一个 pr

2023-02-25 16:22 UTC, LeoQuote requested changes
请先将 goinception 和archery 的更改分开提交，因为有依赖版本变化，谢谢

2024-05-07 10:12 UTC, merged