new chart for pint watch
douban/charts pull request #46
Opened 2023-04-24 08:46 UTC by QSummerY

2023-04-24 08:54 UTC, LeoQuote commented
看起来pint 就是watch 一个cm 要不要在values里留一个field，让用户填cm 的名字，然后自动就watch这个cm

2023-04-25 04:35 UTC, LeoQuote requested changes
改个名字就叫pint吧

2023-04-25 04:38 UTC, LeoQuote commented on charts/pint-exporter/values.yaml
> +      }
这个 cm 设置成自动挂载, 不需要用户来写.

2023-04-25 04:42 UTC, QSummerY commented on charts/pint-exporter/values.yaml
> +      }
这个cm也自动挂载？这样是要单独手动创建config cm么

2023-04-25 04:49 UTC, LeoQuote commented on charts/pint-exporter/values.yaml
> +      }
对用户来说就是在 values 里面写配置或已经存在的 cm , 然后你就在里边渲染 cm , 挂载 cm

2023-04-25 06:15 UTC, LeoQuote approved these changes

2023-04-25 06:15 UTC, merged