pr: modify the image address of busybox
douban/charts pull request #93
Opened 2024-07-11 01:39 UTC by visla-xugeng

2024-07-11 02:01 UTC, LeoQuote requested changes
麻烦 bump version

2024-07-11 02:01 UTC, LeoQuote commented on charts/goinception/values.yaml
> +override-configs:
请用驼峰式命名风格

2024-07-11 17:39 UTC, visla-xugeng commented on charts/goinception/values.yaml
> +override-configs:
Just pushed the code again, please let me know if any questions.

2024-07-12 02:09 UTC, LeoQuote approved these changes

2024-07-12 02:10 UTC, LeoQuote commented
麻烦关注下CI的结果，有一个行位的多余空格

2024-07-12 03:37 UTC, merged